[Paths]
items = [
	"always_on_top",
    "powders",
    "granular_soils",
    "sculks",
    "grasses",
    "mosses",
    "wet_soils",
    "crumbly_soils",
    "dry_soils",
    "non_full_hitbox"
]

[Bricks]
items = [
    "cut_copper_like_bricks",
    "stone_bricks_like_bricks",
    "mud_bricks_like_bricks",
    "quartz_brciks_like_bricks",
    "sculk_grime_bricks_like_bricks",
    "resin_brciks_like_bricks",
    "nether_bricks_like_bricks",
    "dacite_bricks_like_bricks",
    "sculk_stone_tiles_like_bricks",
    "cut_gloomslate_like_bricks",
    "chalk_bricks_like_bricks",
    "chiseled_mega_meteorid_brick_like_bricks",
    "brimstone_bricks_like_bricks",
    "deepslate_tiles_like_bricks"
]

[Rocks]
items = [
    "bedrock",
    "raw_ores",
    "cobblestones",
    "gems",
    "crystals",
    "special_rocks",
    "slates",
    "rocks",
    "stones",
    "obsidians"
]

