order = [
    "minecraft/magma",
	"biomesoplenty/null_block",
	"regions_unexplored/ash",
	"regions_unexplored/volcanic_ash",
	"minecraft/snow",
    "minecraft/white_concrete_powder",
    "minecraft/light_gray_concrete_powder",
    "minecraft/gray_concrete_powder",
    "minecraft/black_concrete_powder",
    "minecraft/brown_concrete_powder",
    "minecraft/red_concrete_powder",
    "minecraft/orange_concrete_powder",
    "minecraft/yellow_concrete_powder",
    "minecraft/lime_concrete_powder",
    "minecraft/green_concrete_powder",
    "minecraft/cyan_concrete_powder",
    "minecraft/light_blue_concrete_powder",
    "minecraft/blue_concrete_powder",
    "minecraft/purple_concrete_powder",
    "minecraft/magenta_concrete_powder",
    "minecraft/pink_concrete_powder",
	"biomesoplenty/black_sand",
    "biomeswevegone/black_sand",
	"biomeswevegone/white_sand",
    "biomesoplenty/white_sand",
	"biomeswevegone/windswept_sand",
    "biomesoplenty/orange_sand",
    "biomeswevegone/blue_sand",
    "biomeswevegone/purple_sand",
    "minecraft/suspicious_sand",
    "minecraft/sand",
    "biomeswevegone/cracked_sand",
    "minecraft/red_sand",
    "biomeswevegone/cracked_red_sand",
    "minecraft/suspicious_gravel",
    "minecraft/gravel",
	"deeperdarker/gloomy_sculk",
	"minecraft/sculk",
	"deeperdarker/echo_soil",
	"deeperdarker/blooming_sculk_stone_top",
	"minecraft/warped_nylium",
	"minecraft/warped_nylium_side",
    "minecraft/crimson_nylium",
	"minecraft/crimson_nylium_side",
    "regions_unexplored/brimsprout_nylium",
    "pyrellium/burning_nylium",
    "regions_unexplored/glistering_nylium",
	"regions_unexplored/cobalt_nylium",
	"betternether/mushroom_grass_top",
	"betternether/jungle_grass_top",
	"betternether/sepia_mushroom_grass_top",
	"betternether/swampland_grass",
	"regions_unexplored/viridescent_nylium",
	"minecraft/fake_podzol_snow",
	"minecraft/podzol_top",
	"minecraft/podzol_side",
	"regions_unexplored/peat_podzol_top",
	"regions_unexplored/silt_podzol_top",
	"minecraft/fake_mycelium_snow",
	"minecraft/mycelium_top",
	"minecraft/mycelium_side",
	"betternether/nether_mycelium_top",
	"minecraft/fake_grass_snow",
	"minecraft/grass_block_top",
	"regions_unexplored/ru_grass_block_top",
	"minecraft/grass_block_snow",
	"minecraft/grass_block_side_overlay",
	"minecraft/grass_block_side",
	"biomesoplenty/origin_grass_block_top",
	"regions_unexplored/alpha_grass_block_top",
	"biomesoplenty/algal_end_stone",
    "deeperdarker/blooming_moss_block",
    "regions_unexplored/mycotoxic_moss",
	"betternether/nether_moss_top",
	"regions_unexplored/prismoss_overlay_top",
	"biomesoplenty/glowing_moss_block",
    "minecraft/pale_moss_block",
    "minecraft/moss_block",
    "biomesoplenty/mossy_black_sand_top",
	"minecraft/muddy_mangrove_roots_top",
	"minecraft/muddy_mangrove_roots_side",
	"minecraft/clay",
	"biomeswevegone/sandy_dirt",
    "minecraft/soul_soil",
    "regions_unexplored/ashen_dirt",
    "regions_unexplored/peat_coarse_dirt",
    "regions_unexplored/peat_dirt",
	"biomeswevegone/lush_dirt",
    "regions_unexplored/silt_coarse_dirt",
    "regions_unexplored/silt_dirt",
    "minecraft/rooted_dirt",
    "minecraft/coarse_dirt",
    "minecraft/dirt",
	"biomeswevegone/packed_pale_mud",
	"minecraft/packed_mud",
    "biomesoplenty/dried_salt",
	"biomeswevegone/peat",
    "betternether/cincinnasite_tiles_small",
	"betternether/nether_brick_tile_small",
    "betternether/blue_obsidian_tile_small",
    "betternether/obsidian_tile_small",
    "deeperdarker/cut_sculk_stone",
    "deeperdarker/gloomslate_tiles",
    "minecraft/oxidized_cut_copper",
	"minecraft/weathered_cut_copper",
	"minecraft/exposed_cut_copper",
	"minecraft/cut_copper",
	"minecraft/purpur_block",
	"cobblemon/tumblestone_bricks",
    "cobblemon/black_tumblestone_bricks",
    "cobblemon/sky_tumblestone_bricks",
    "mega_showdown/mega_meteorid_brick",
    "betternether/blue_obsidian_bricks",
    "betternether/obsidian_bricks",
    "deeperdarker/sculk_stone_bricks",
    "deeperdarker/gloomslate_bricks",
    "minecraft/mossy_stone_bricks",
	"minecraft/cracked_stone_bricks",
	"minecraft/stone_bricks",
    "minecraft/cinnabar_bricks",
    "minecraft/sulfur_bricks",
	"minecraft/cracked_polished_blackstone_bricks",
    "minecraft/polished_blackstone_bricks",
    "betternether/basalt_bricks",
    "minecraft/cracked_deepslate_bricks",
    "minecraft/deepslate_bricks",
    "minecraft/tuff_bricks",
    "minecraft/end_stone_bricks",
	"biomeswevegone/pale_mud_bricks",
    "minecraft/mud_bricks",
    "biomeswevegone/mossy_red_rock_bricks",
    "biomeswevegone/cracked_red_rock_bricks",
    "biomeswevegone/red_rock_bricks",
    "minecraft/quartz_bricks",
	"deeperdarker/sculk_grime_bricks",
    "minecraft/bricks",
    "minecraft/resin_bricks",
	"minecraft/cracked_nether_bricks",
    "minecraft/nether_bricks",
    "minecraft/red_nether_bricks",
	"biomeswevegone/mossy_dacite_bricks",
    "biomeswevegone/cracked_dacite_bricks",
    "biomeswevegone/chiseled_dacite_bricks",
    "biomeswevegone/dacite_bricks",
    "biomeswevegone/mossy_white_dacite_bricks",
    "biomeswevegone/cracked_white_dacite_bricks",
    "biomeswevegone/chiseled_white_dacite_bricks",
    "biomeswevegone/white_dacite_bricks",
	"deeperdarker/sculk_stone_tiles",
    "deeperdarker/cut_gloomslate",
    "regions_unexplored/chalk_bricks",
	"mega_showdown/chiseled_mega_meteorid_brick",
    "biomesoplenty/brimstone_bricks",
    "betternether/obsidian_rod_tiles",
    "betternether/blue_obsidian_rod_tiles",
    "minecraft/cracked_deepslate_tiles",
    "minecraft/deepslate_tiles",
	"betternether/blue_weeping_obsidian",
    "betternether/weeping_obsidian",
    "betternether/blue_crying_obsidian",
    "regions_unexplored/cobalt_obsidian",
    "minecraft/crying_obsidian",
    "betternether/blue_obsidian",
    "minecraft/bedrock",
	"minecraft/raw_gold_block",
    "minecraft/raw_copper_block",
    "minecraft/raw_iron_block",
    "regions_unexplored/raw_redstone_block",
	"deeperdarker/cobbled_sculk_stone",
    "biomeswevegone/dacite_cobblestone",
    "biomeswevegone/white_dacite_cobblestone",
    "minecraft/mossy_cobblestone",
    "minecraft/cobblestone",
	"deeperdarker/cobbled_gloomslate",
    "minecraft/cobbled_deepslate",
    "minecraft/prismarine",
	"cobblemon/tumblestone_block",
    "cobblemon/black_tumblestone_block",
    "cobblemon/sky_tumblestone_block",
	"biomesoplenty/rose_quartz_block",
    "pyrellium/opal_block",
	"pyrellium/clear_opal_block",
    "minecraft/amethyst_block",
	"pyrellium/clear_amethyst_block",
	"biomesoplenty/flesh",
    "biomesoplenty/porous_flesh",
	"mega_showdown/mega_meteorid_radiated_block",
    "mega_showdown/mega_meteorid_block",
	"minecraft/dripstone_block",
    "minecraft/end_stone",
	"biomesoplenty/brimstone",
	"minecraft/blackstone_top",
	"minecraft/blackstone",
	"minecraft/netherrack",
	"biomesoplenty/thermal_calcite",
	"biomesoplenty/thermal_calcite_2",
	"biomesoplenty/thermal_calcite_3",
	"biomesoplenty/thermal_calcite_4",
	"biomesoplenty/thermal_calcite_5",
	"minecraft/calcite",
    "minecraft/smooth_basalt",
    "minecraft/basalt_top",
    "minecraft/basalt_side",
	"minecraft/tuff",
	"deeperdarker/gloomslate",
	"minecraft/deepslate_top",
	"minecraft/deepslate",
	"biomeswevegone/dacite",
    "biomeswevegone/white_dacite",
    "minecraft/cinnabar",
    "minecraft/potent_sulfur",
    "minecraft/sulfur",
	"minecraft/andesite",
    "minecraft/diorite",
    "minecraft/granite",
	"deeperdarker/sculk_stone",
    "biomeswevegone/red_rock",
    "regions_unexplored/argillite",
    "regions_unexplored/chalk",
	"biomeswevegone/mossy_stone",
    "regions_unexplored/mossy_stone",
    "biomeswevegone/rocky_stone",
    "minecraft/stone",
	"minecraft/mud",
	"minecraft/powder_snow",
	"minecraft/soul_sand"
]