#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 12 09:24:54 EET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=9
shaderPack=SEUS PTGI HRR Test 2.1.zip
enableShaders=true
