#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 12 12:39:16 EET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=\u00A71\u00A7lBetter\u00A7f\u00A7lVoxels v1.7.zip
